trigger:
  branches:
    include:
      - master

variables:
  resourceGroupName: 'DevOps_Pipeline'
  aksClusterName: 'AssignmentAKSCluster'
  location: 'northeurope'
  acrName: 'private4assignment'
  ingressControllerNamespace: 'ingress-basic'

stages:
- stage: BuildInfrastructure
  jobs:
  - job: DeployACRandAKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'assignment'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create ACR
          az acr create --name $(acrName) --resource-group $(resourceGroupName) --sku Basic --location $(location)
          
          # Create AKS
          az aks create --name $(aksClusterName) --resource-group $(resourceGroupName) --generate-ssh-keys --attach-acr $(acrName) || true

  - job: DeployIngressController
    displayName: 'Deploy Ingress Controller'
    dependsOn: DeployACRandAKS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'assignment' 
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Install Helm
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

          # Get AKS credentials
          az aks get-credentials --name $(aksClusterName) --resource-group $(resourceGroupName) --overwrite-existing

          # Install Ingress Controller
          kubectl create namespace $(ingressControllerNamespace)
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm install nginx-ingress ingress-nginx/ingress-nginx -n $(ingressControllerNamespace)
